# Generated by Django 5.0 on 2025-07-21 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('dateTimeCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('progressStatus', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='not_started', max_length=20)),
                ('importanceRating', models.CharField(choices=[('optional', 'Optional'), ('medium', 'Medium'), ('important', 'Important')], default='optional', max_length=20)),
            ],
            options={
                'ordering': ['-dateTimeCreated'],
            },
        ),
    ]
